//import
import java.awt.Image;
import java.awt.event.ActionEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.Timer;


public class loadingScreen extends javax.swing.JFrame {

   Timer timer;
   int time;
    public loadingScreen() {
        initComponents();
        {
         Icon i = lblLogo.getIcon(); //resizing the image
        ImageIcon imgIcon = (ImageIcon) i;
        Image image = imgIcon.getImage ().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_SMOOTH); 
        lblLogo.setIcon(new ImageIcon (image));
        
        timer = new Timer(40, (ActionEvent e) -> {
            pbLoadingBar.setValue(time); //loading bar and when it fills, it opens up a new window
            time++;
             // Update text based on time value
    if (time >= 0 && time < 20) {
        txtWelcome.setText("W.............................");
    } else if (time >= 20 && time < 40) {
        txtWelcome.setText("Welcome");
    } else if (time >= 40 && time < 60) {
        txtWelcome.setText("Welcome to");
    } else if (time >= 60 && time <= 80) {
        txtWelcome.setText("Welcome to Hotel");
    } else if (time >= 80 && time <= 100) {
        txtWelcome.setText("WELCOME TO HOTEL AMIGGAS");
    }
            if(time==100){
                Menu menu = new Menu();
                menu.setVisible(true);
                this.dispose();
            }
        });
        timer.start();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHotelNigo1 = new javax.swing.JLabel();
        pnlBg = new javax.swing.JPanel();
        txtWelcome = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        pbLoadingBar = new javax.swing.JProgressBar();
        lblHoteAmiggas = new javax.swing.JLabel();

        lblHotelNigo1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 64)); // NOI18N
        lblHotelNigo1.setForeground(new java.awt.Color(255, 255, 255));
        lblHotelNigo1.setText("HOTEL AMIGGAS");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlBg.setBackground(new java.awt.Color(28, 25, 41));

        txtWelcome.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 28)); // NOI18N
        txtWelcome.setForeground(new java.awt.Color(204, 204, 204));
        txtWelcome.setText("WELCOME TO HOTEL AMIGGAS");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AmiggasLogo.png"))); // NOI18N

        pbLoadingBar.setBackground(new java.awt.Color(204, 204, 204));
        pbLoadingBar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        pbLoadingBar.setForeground(new java.awt.Color(0, 0, 0));
        pbLoadingBar.setToolTipText("");
        pbLoadingBar.setStringPainted(true);

        lblHoteAmiggas.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 64)); // NOI18N
        lblHoteAmiggas.setForeground(new java.awt.Color(255, 255, 255));
        lblHoteAmiggas.setText("HOTEL AMIGGAS");

        javax.swing.GroupLayout pnlBgLayout = new javax.swing.GroupLayout(pnlBg);
        pnlBg.setLayout(pnlBgLayout);
        pnlBgLayout.setHorizontalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBgLayout.createSequentialGroup()
                        .addComponent(pbLoadingBar, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBgLayout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(311, 311, 311))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBgLayout.createSequentialGroup()
                        .addComponent(txtWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(252, 252, 252))))
            .addGroup(pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBgLayout.createSequentialGroup()
                    .addContainerGap(339, Short.MAX_VALUE)
                    .addComponent(lblHoteAmiggas, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(270, 270, 270)))
        );
        pnlBgLayout.setVerticalGroup(
            pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBgLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(txtWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pbLoadingBar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(pnlBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBgLayout.createSequentialGroup()
                    .addContainerGap(495, Short.MAX_VALUE)
                    .addComponent(lblHoteAmiggas, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(166, 166, 166)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loadingScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblHoteAmiggas;
    private javax.swing.JLabel lblHotelNigo1;
    private javax.swing.JLabel lblLogo;
    public javax.swing.JProgressBar pbLoadingBar;
    private javax.swing.JPanel pnlBg;
    private javax.swing.JLabel txtWelcome;
    // End of variables declaration//GEN-END:variables
}
