
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form loadingScreen
     */
    public Menu() {
        initComponents();
        Icon i = lblLogo.getIcon(); //resizing the image
        ImageIcon imgIcon = (ImageIcon) i;
        Image image = imgIcon.getImage ().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_SMOOTH); 
        lblLogo.setIcon(new ImageIcon (image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pblBg = new javax.swing.JPanel();
        lblHotelNigo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        btnLogIn = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pblBg.setBackground(new java.awt.Color(28, 25, 41));
        pblBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHotelNigo.setBackground(new java.awt.Color(255, 255, 255));
        lblHotelNigo.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 64)); // NOI18N
        lblHotelNigo.setForeground(new java.awt.Color(255, 255, 255));
        lblHotelNigo.setText("HOTEL AMIGGAS");
        pblBg.add(lblHotelNigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, 76));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AmiggasLogo.png"))); // NOI18N
        pblBg.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 360, 410));

        btnLogIn.setBackground(new java.awt.Color(153, 255, 153));
        btnLogIn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLogIn.setForeground(new java.awt.Color(0, 0, 0));
        btnLogIn.setText("LOG IN");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        pblBg.add(btnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 178, -1));

        btnExit.setBackground(new java.awt.Color(255, 51, 0));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 0, 0));
        btnExit.setText("CLOSE");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pblBg.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 610, 178, -1));

        getContentPane().add(pblBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        //if the user clicks the play button
        logIn login = new logIn();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure to exit?", "EXIT APPLICATION", JOptionPane.YES_NO_OPTION);
        //confirming the user if the user really wants to leave
        if (confirm == 0)//if yes
        System.exit(0);//ending the program
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnExit;
    public javax.swing.JButton btnLogIn;
    private javax.swing.JLabel lblHotelNigo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pblBg;
    // End of variables declaration//GEN-END:variables
}
